import Particles from "react-particles-js";
import React from "react";

function Particle() {
    return <>
        <Particles width="100%" height="100vh" params={
            {
                particles:{
                    number:{
                        value:125,
                        density:{
                            enable:true,
                            value_area:2884.3380444188083
                        }
                    },
                    color:{
                        value:"#c3cd26"
                    },
                    shape:{
                        type:"circle",
                        stroke:{
                            width:0,
                            color:"#000000"
                        },
                        polygon:{
                            nb_sides:3
                        },
                        image:{
                            src:"img/github.svg",
                            width:100,
                            height:100
                        }
                    },
                    opacity:{
                        value:0.8973496138191848,
                        random:false,
                        anim:{
                            enable:true,
                            speed:1.5418949076891875,
                            opacity_mean:0.1,
                            sync:false}
                    },
                    size:{
                        value:0,
                        random:true,
                        anim:{
                            enable:false,
                            speed:40,
                            size_min:0.1,
                            sync:false
                        }
                    },
                    line_linked:{
                        enable:true,
                        distance:256.38560394833854,
                        color:"#ffffff",
                        opacity:0.12018075185078368,
                        width:0.8012050123385578
                    },
                    move:{
                        enable:true,
                        speed:2,
                        direction:"none",
                        random:false,
                        straight:false,
                        out_mode:"out",
                        bounce:false,
                        attract:{
                            enable:false,
                            rotateX:600,
                            rotateY:1200
                        }
                    }
                },
                interactivity:{
                    detect_on:"canvas",
                    events:{
                        onhover:{
                            enable:true,
                            mode:"repulse"
                        },
                        onclick:{
                            enable:true,
                            mode:"push"
                        },
                        resize:true
                    },
                    modes:{
                        grab:{
                            distance:400,
                            line_linked:{
                                opacity:1
                            }
                        },
                        bubble:{
                            distance:400,
                            size:40,
                            duration:2,
                            opacity:8,
                            speed:3
                        },
                        repulse:{
                            distance:200,
                            duration:0.4
                        },
                        push:{
                            particles_nb:4
                        },
                        remove:{
                            particles_nb:2
                        }
                    }
                },
                retina_detect:true
            }
        } />
    </>
}

export default Particle;
